title:              Zephyr
email:              nainani.jatin.0@gmail.com
description:        An aspiring AI Scientist who wants to contribute to research 
author:             Jatin Nainani
baseurl:            ""
url:                "https://nainanijatinz.github.io"

# Social Profiles
# twitter_username: 
github_username: NainaniJatinZ
# facebook_username:  
# instagram_username: 
linkedin_username: jatin-nainani-a6b2331b3

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
